// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Author struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Born  string  `json:"born"`
	Died  string  `json:"died"`
	Books []*Book `json:"books"`
}

type Book struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Publication int32     `json:"publication"`
	Authors     []*Author `json:"authors"`
	Genres      []*Genre  `json:"genres"`
	Pages       int32     `json:"pages"`
	Language    *Language `json:"language"`
}

type Genre struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Books []*Book `json:"books"`
}

type Language struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Books []*Book `json:"books"`
}

type Mutation struct {
}

type NewAuthor struct {
	Name    string   `json:"name"`
	Born    string   `json:"born"`
	Died    string   `json:"died"`
	BooksID []string `json:"booksID"`
}

type NewBook struct {
	Name        string   `json:"name"`
	Publication int32    `json:"publication"`
	AuthorsID   []string `json:"authorsID"`
	GenresID    []string `json:"genresID"`
	LanguageID  string   `json:"languageID"`
	Pages       int32    `json:"pages"`
}

type NewGenre struct {
	Name string `json:"name"`
}

type NewLanguage struct {
	Name string `json:"name"`
}

type Query struct {
}

type UpdateAuthor struct {
	ID      string   `json:"id"`
	Name    string   `json:"name"`
	Born    string   `json:"born"`
	Died    string   `json:"died"`
	BooksID []string `json:"booksID"`
}

type UpdateBook struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	Publication int32    `json:"publication"`
	AuthorIDs   []string `json:"authorIDs"`
	GenreIDs    []string `json:"genreIDs"`
	LanguageID  string   `json:"languageID"`
	Pages       int32    `json:"pages"`
}

type UpdateGenre struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type UpdateLanguage struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
